import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const montserratSemiBold = localFont({
  src: "./fonts/montserrat/static/Montserrat-SemiBold.ttf",
  variable:"--font-montserrat-semibold",
  weight: "100 900"
});

const montserratMedium = localFont({
  src: "./fonts/montserrat/static/Montserrat-Medium.ttf",
  variable:"--font-montserrat-medium",
  weight: "100 900"
});

const montserratRegular = localFont({
  src: "./fonts/montserrat/static/Montserrat-Regular.ttf",
  variable:"--font-montserrat-regular",
  weight: "100 900"
});

const montserratLight = localFont({
  src: "./fonts/montserrat/static/Montserrat-Light.ttf",
  variable:"--font-montserrat-light",
  weight: "100 900"
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          ${montserratSemiBold.variable} 
          ${montserratMedium.variable}
          ${montserratRegular.variable} 
          ${montserratLight.variable}
          antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
